/**********************************************************************************************
* Java Program Name
***********************************************************************************************
* Project/Program description
*______________________________________________________________________________________________
* Paramveer Singh
* 1/16/19
* CMSC - 255-3-4-2019Spring
***********************************************************************************************/

public class Hello {
	public static void printHeading(){
	System.out.println("Paramveer Singh");
	System.out.println("Hello.Java");
	System.out.println("Getting familiar with Java");
	System.out.println("1/19/2019");
	System.out.println("CMSC - 255-3-4-2019");
	}
	
	public static void main(String [] args){
	printHeading();
	System.out.println("Hello");
	}
}